events {
    worker_connections 1024;
}

http {
    log_format json_analytics escape=json '{'
        '"source_ip": "$remote_addr", '
        '"timestamp": "$time_iso8601", '
        '"method": "$request_method", '
        '"path": "$request_uri", '
        '"status": "$status", '
        '"response_size": "$bytes_sent"'
    '}';

    access_log /var/log/nginx/hng-access.log json_analytics;
    error_log /var/log/nginx/error.log;

    # 1. Default Server: IP-only traffic routes to Nextcloud
    server {
        listen 80 default_server;
        
        location / {
            proxy_pass http://nextcloud:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            client_max_body_size 512M;
        }
    }

    # 2. Domain Server: Domain traffic routes to the Python Dashboard
    server {
        listen 80;
        # Route traffic from the provided Azure domain to the Dashboard
        server_name nepobaby.eastus.cloudapp.azure.com;
        
        location / {
            # Route to detector dashboard. 
            # Note: 172.17.0.1 is the default Docker bridge IP. 
            # Since detector runs in host network mode, it binds to the host's port 5000.
            proxy_pass http://172.17.0.1:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
